sudo: false

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- gcloud components install cloud-datastore-emulator

before_script:
- gcloud beta emulators datastore start --consistency 1.0 --no-store-on-disk &
- $(gcloud beta emulators datastore env-init)

language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: test
      node_js: "8"
      script: npm test && npm run coverage
